name: muay-thai
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - gradio_imageslider
      - gradio
      - matplotlib
      - opencv-python
      - open3d
      - torch==2.11.0+cu128
      - torchvision==0.26.0+cu128
      - torchaudio==2.11.0+cu128
